/**
 * Type Contracts: Agentic Workflow Graph
 *
 * These types define the contracts between backend and frontend for the
 * auto-generated workflow graph feature.
 */

// ============================================================================
// Existing Types (for reference - defined in ui-components)
// ============================================================================

/**
 * Existing GraphData interface from use-trace-graph.ts
 * This remains unchanged for backward compatibility with manual metadata.
 */
export interface GraphData {
  parentNodeId?: string;
  nodeId: string;
  spanId: string;
  nodeType: string;
  displayName: string;
  spanName: string;
}

// ============================================================================
// New Types for Auto-Generated Workflow Graph
// ============================================================================

/**
 * Valid node types for workflow graph nodes.
 * These map to icon/color styling in node-styling.ts.
 */
export type WorkflowNodeType =
  | "llm"
  | "tool"
  | "agent"
  | "retrieval"
  | "router"
  | "memory"
  | "default";

/**
 * Intermediate grouping structure used during auto-generation.
 * Groups spans by their composite key (parentSpanId:spanName).
 *
 * Note: toolName field removed - with normalizer fix, tool call spans
 * have tool name as their spanName (e.g., "search_web" instead of "toolCall").
 */
export interface NodeGroup {
  /** Composite key: `${parentSpanId || 'root'}:${spanName}` */
  key: string;

  /** Parent span ID, undefined for root-level spans */
  parentSpanId?: string;

  /** Span operation name (e.g., "generateText", "search_web", "read_file") */
  spanName: string;

  /** All span IDs belonging to this group */
  spanIds: string[];

  /** First span's start time for ordering */
  firstStartTime: number;
}

/**
 * A grouped representation of one or more spans in the workflow graph.
 */
export interface WorkflowNode {
  /** Unique node identifier: `${parentSpanId || 'root'}:${spanName}` */
  nodeId: string;

  /** Human-readable label for display */
  displayName: string;

  /** Inferred operation type for styling */
  nodeType: WorkflowNodeType;

  /** All span IDs grouped in this node */
  spanIds: string[];

  /** Parent node ID for hierarchy (undefined for root nodes) */
  parentNodeId?: string;
}

/**
 * A directional edge representing execution flow between nodes.
 */
export interface WorkflowEdge {
  /** Edge identifier: `${source}->${target}` */
  id: string;

  /** Source node ID */
  source: string;

  /** Target node ID */
  target: string;

  /** True if both A->B and B->A transitions occurred */
  bidirectional: boolean;
}

/**
 * Complete workflow graph structure returned by the backend.
 */
export interface WorkflowGraph {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];

  /** True if graph was auto-generated, false if from manual metadata */
  isAutoGenerated: boolean;
}

// ============================================================================
// Extended GraphData for Backend Response
// ============================================================================

/**
 * Extended graph data item that includes auto-generation fields.
 * Backward compatible: manual metadata responses won't have spanIds/spanCount.
 */
export interface ExtendedGraphData extends GraphData {
  /** All span IDs in this node (auto-generated only) */
  spanIds?: string[];

  /** Number of spans (auto-generated only) */
  spanCount?: number;
}

// ============================================================================
// React Flow Extension Types
// ============================================================================

/**
 * Extended node data for React Flow TraceNode component.
 */
export interface TraceNodeData {
  /** Display label */
  label: string;

  /** All span IDs for click cycling */
  spanIds: string[];

  /** Number of spans (for badge display) */
  spanCount: number;

  /** Current selected span index (for cycling) */
  currentIndex: number;

  /** Node type for styling */
  nodeType: WorkflowNodeType;

  /** Primary span ID (first in list) */
  spanId: string;

  /** Node type color from theme */
  color: string;

  /** Node type icon (iconify format) */
  icon: string;

  /** Branch family color */
  branchColor: string;

  /** Click handler */
  onNodeClick?: (spanId: string) => void;
}

/**
 * State for tracking selection cycling per node.
 * Used when user clicks repeatedly on a multi-span node.
 */
export interface NodeSelectionState {
  /** Map of nodeId to selection state */
  [nodeId: string]: {
    /** All span IDs in the node */
    spanIds: string[];
    /** Currently selected span index (0-based) */
    currentIndex: number;
  };
}

/**
 * Selection indicator format for multi-span nodes.
 * Shows "2/5" when currentIndex=1 and spanCount=5.
 */
export interface SelectionIndicator {
  /** Current position (1-based for display) */
  current: number;
  /** Total number of spans */
  total: number;
  /** Formatted string (e.g., "2/5") */
  display: string;
}

/**
 * Graph loading state for UI feedback.
 */
export type GraphLoadingState = "loading" | "ready" | "empty" | "error";

/**
 * Graph component state including loading and error states.
 */
export interface WorkflowGraphState {
  /** Current loading state */
  loadingState: GraphLoadingState;
  /** Error message if loadingState is "error" */
  errorMessage?: string;
  /** Nodes (available when loadingState is "ready") */
  nodes: WorkflowNode[];
  /** Edges (available when loadingState is "ready") */
  edges: WorkflowEdge[];
  /** Whether this is auto-generated or from manual metadata */
  isAutoGenerated: boolean;
}

/**
 * Hook props for useWorkflowGraph (new hook for auto-generated graphs).
 */
export interface UseWorkflowGraphProps {
  /** Raw span data from trace */
  spans: Array<{
    spanId: string;
    parentSpanId?: string;
    name: string;  // After normalizer fix, tool calls have tool name here
    type: string;
    startTime: number;
  }>;
}

/**
 * Hook result for useWorkflowGraph.
 */
export interface UseWorkflowGraphResult {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Type guard to check if graph data includes auto-generated fields.
 */
export function isAutoGeneratedGraphData(
  data: GraphData | ExtendedGraphData
): data is ExtendedGraphData {
  return "spanIds" in data && Array.isArray(data.spanIds);
}

/**
 * Type guard to validate WorkflowNodeType.
 */
export function isValidNodeType(type: string): type is WorkflowNodeType {
  return [
    "llm",
    "tool",
    "agent",
    "retrieval",
    "router",
    "memory",
    "default",
  ].includes(type);
}
