// Auto-generated types from Puzzlet
// Do not edit this file directly

interface ObjectEntry<I, O> { kind: 'object'; input: I; output: O }
interface TextEntry<I, O>   { kind: 'text';   input: I; output: O }
interface ImageEntry<I, O>  { kind: 'image';  input: I; output: O }

interface MathIn { [key: string]: any }

interface MathOut { [key: string]: string }

interface Test$Math2In {
  /**
   * The math question or topic the student needs help with
   */
  userMessage: string;
}


interface Test$Math2Out {
  /**
   * The answer to the math question
   */
  answer: string;
}


type Math = ObjectEntry<MathIn, MathOut>;

type Test$Math2 = ObjectEntry<Test$Math2In, Test$Math2Out>;

interface PuzzletTypes {
  "math.prompt.mdx": Math,
  "test/math2.prompt.mdx": Test$Math2,
}

export default PuzzletTypes;