"""Programmatic type-safety tests for the Executor protocol + generated types.

Python equivalent of TypeScript's `generate-types.e2e.test.ts`. Uses mypy
as the static checker (the Python ecosystem's analogue of tsc) and asserts
on specific error codes — not just "any error" — so a regression that
shifts error location or weakens the contract fails loudly.

The generated-types fixture embedded in each consumer is hand-written in
the EXACT shape `@agentmark-ai/shared-utils generateTypeDefinitions(...,
"python")` emits. Shape correctness is already verified by
`cli/test/generate-types.test.ts` on the TS side; this test focuses on
the CONSUMPTION side — that the emitted types produce a type-safe pipeline
when consumed through the Executor protocol + Pydantic models.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

import pytest


# ---------- Fixtures: types file matching the generator's output shape ----------

GENERATED_TYPES_PY = dedent('''\
    # Auto-generated types from AgentMark (fixture mirroring generator output)
    # Do not edit this file directly

    from __future__ import annotations

    from typing import Any, Literal, NotRequired, TypedDict


    class GreetIn(TypedDict):
        name: str


    class GreetOut(TypedDict):
        pass


    class Greet(TypedDict):
        input: GreetIn
        output: str
        kind: Literal["text"]


    class MathIn(TypedDict):
        question: str


    class MathOut(TypedDict):
        answer: int


    class Math(TypedDict):
        input: MathIn
        output: MathOut
        kind: Literal["object"]


    class SearchWebArgs(TypedDict):
        query: str


    class Tools(TypedDict):
        search_web: SearchWebArgs


    class AgentmarkTypes(TypedDict):
        # Keys map prompt paths to their shape. The generator emits this
        # as a TypedDict with string-literal keys; mypy validates assignment.
        greet: Greet
        math: Math
''')


def _mypy_path() -> str:
    # Prefer the venv-local mypy so the version is pinned with prompt-core-python.
    venv_mypy = (
        Path(__file__).resolve().parents[1] / ".venv" / "bin" / "mypy"
    )
    if venv_mypy.is_file():
        return str(venv_mypy)
    from_path = shutil.which("mypy")
    if from_path:
        return from_path
    pytest.skip("mypy not available")


def _run_mypy(*files: Path, strict: bool = True) -> tuple[int, str, str]:
    """Run mypy and return (exitcode, stdout, stderr)."""
    mypy = _mypy_path()
    cmd = [
        mypy,
        "--hide-error-context",
        "--show-error-codes",
        "--no-color-output",
        "--no-error-summary",
        "--follow-imports=silent",
        "--show-absolute-path",
    ]
    if strict:
        cmd.append("--strict")
    cmd.extend(str(f) for f in files)
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    return proc.returncode, proc.stdout, proc.stderr


def _write_pair(tmp_path: Path, consumer_body: str) -> tuple[Path, Path]:
    types_file = tmp_path / "agentmark_types.py"
    types_file.write_text(GENERATED_TYPES_PY)
    consumer = tmp_path / "consumer.py"
    consumer.write_text(consumer_body)
    return types_file, consumer


def _error_codes(stdout: str) -> list[str]:
    """Extract mypy error codes from stdout, e.g. ['typeddict-item', ...]."""
    codes: list[str] = []
    for line in stdout.splitlines():
        # mypy format: FILE:LINE: error: MSG  [CODE]
        if "error:" in line and "[" in line and line.rstrip().endswith("]"):
            code = line.rstrip().rsplit("[", 1)[-1].rstrip("]")
            codes.append(code)
    return codes


# ---------- Positive cases: valid usage must type-check ----------


def test_generated_types_import_and_use_cleanly(tmp_path: Path):
    consumer_body = dedent('''\
        from agentmark_types import AgentmarkTypes, GreetIn, MathOut, Tools

        def read_shape(d: AgentmarkTypes) -> None:
            name: str = d["greet"]["input"]["name"]
            answer: int = d["math"]["output"]["answer"]
            tool_query: str = d["math"]["output"] and "unused"  # dummy
            _ = name, answer, tool_query
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, err = _run_mypy(consumer)
    assert code == 0, f"mypy should pass; got:\n{out}\n{err}"


def test_executor_protocol_accepts_minimal_impl(tmp_path: Path):
    consumer_body = dedent('''\
        from __future__ import annotations
        from collections.abc import AsyncIterator
        from agentmark.prompt_core import (
            ExecCtx, Executor, ExecutorCapabilities, FinishEvent,
            ObjectFinalEvent, ObjectStreamEvent, TextDeltaEvent,
            TextStreamEvent, UsageData,
        )

        class MyExecutor:
            name: str = "my-sdk"

            def capabilities(self) -> ExecutorCapabilities:
                return ExecutorCapabilities(text=True, object=True)

            async def execute_text(
                self, formatted: object, ctx: ExecCtx
            ) -> AsyncIterator[TextStreamEvent]:
                yield TextDeltaEvent(text="hi")
                yield FinishEvent(
                    reason="stop",
                    usage=UsageData(input_tokens=1, output_tokens=1),
                )

            async def execute_object(
                self, formatted: object, ctx: ExecCtx
            ) -> AsyncIterator[ObjectStreamEvent]:
                yield ObjectFinalEvent(value={"ok": True})
                yield FinishEvent(
                    reason="stop",
                    usage=UsageData(input_tokens=1, output_tokens=1),
                )

        def takes_executor(ex: Executor) -> None:
            _ = ex.name

        takes_executor(MyExecutor())
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, err = _run_mypy(consumer, strict=False)
    assert code == 0, f"mypy should pass; got:\n{out}\n{err}"


def test_object_event_rejected_in_text_stream(tmp_path: Path):
    # Kind-split parity with the TS `@ts-expect-error` test: yielding an
    # object-kind event from a text stream is a static type error, not just a
    # runtime conformance failure.
    consumer_body = dedent('''\
        from __future__ import annotations
        from collections.abc import AsyncIterator
        from agentmark.prompt_core import (
            ObjectDeltaEvent, TextDeltaEvent, TextStreamEvent,
        )

        async def text_stream() -> AsyncIterator[TextStreamEvent]:
            yield TextDeltaEvent(text="ok")
            yield ObjectDeltaEvent(partial={"a": 1})  # wrong kind
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, err = _run_mypy(consumer, strict=False)
    assert code != 0, f"mypy should reject an object event in a text stream:\n{out}"
    assert "ObjectDeltaEvent" in out or "yield" in out


def test_pydantic_basemodel_flows_through_object_final_event(tmp_path: Path):
    consumer_body = dedent('''\
        from __future__ import annotations
        from pydantic import BaseModel
        from agentmark.prompt_core import ObjectFinalEvent

        class Answer(BaseModel):
            answer: int
            explanation: str

        # Pydantic instances are valid as `value: Any` on ObjectFinalEvent.
        ev: ObjectFinalEvent = ObjectFinalEvent(value=Answer(answer=42, explanation="x"))
        # model_dump() preserves typing on the Pydantic side.
        dumped: dict[str, object] = Answer(answer=1, explanation="y").model_dump()
        _ = ev, dumped
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, err = _run_mypy(consumer, strict=False)
    assert code == 0, f"mypy should pass; got:\n{out}\n{err}"


# ---------- Negative cases: invalid usage MUST produce specific mypy errors ----------


def test_rejects_wrong_prompt_key(tmp_path: Path):
    """Accessing an undeclared key on AgentmarkTypes TypedDict is a mypy error."""
    consumer_body = dedent('''\
        from agentmark_types import AgentmarkTypes

        def oops(d: AgentmarkTypes) -> None:
            # Undeclared TypedDict key — mypy [typeddict-item].
            _ = d["does_not_exist"]
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, _err = _run_mypy(consumer)
    assert code != 0, f"mypy should fail; got clean output:\n{out}"
    assert "typeddict-item" in _error_codes(out), (
        f"expected [typeddict-item] error, got codes: {_error_codes(out)}\n{out}"
    )


def test_rejects_wrong_input_shape(tmp_path: Path):
    """A GreetIn value with the wrong field type fails mypy."""
    consumer_body = dedent('''\
        from agentmark_types import GreetIn

        bad: GreetIn = {"name": 123}  # name must be str
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, _err = _run_mypy(consumer)
    assert code != 0, f"mypy should fail; got clean output:\n{out}"
    codes = _error_codes(out)
    # mypy reports TypedDict value type mismatches as [typeddict-item].
    assert "typeddict-item" in codes, (
        f"expected [typeddict-item], got: {codes}\n{out}"
    )


def test_rejects_missing_required_tool_arg(tmp_path: Path):
    """SearchWebArgs requires `query: str`; omitting it is a mypy error."""
    consumer_body = dedent('''\
        from agentmark_types import SearchWebArgs

        # Missing required 'query' field.
        bad: SearchWebArgs = {}
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, _err = _run_mypy(consumer)
    assert code != 0, f"mypy should fail; got clean output:\n{out}"


def test_rejects_extra_key_on_input(tmp_path: Path):
    """TypedDict rejects unknown keys (generator emits total TypedDicts)."""
    consumer_body = dedent('''\
        from agentmark_types import GreetIn

        # 'extra' is not a declared key on GreetIn.
        bad: GreetIn = {"name": "x", "extra": 1}
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, _err = _run_mypy(consumer)
    assert code != 0, f"mypy should fail; got clean output:\n{out}"


def test_rejects_wrong_agent_event_variant(tmp_path: Path):
    """Using the wrong field on a discriminated event is caught by mypy."""
    consumer_body = dedent('''\
        from agentmark.prompt_core import TextDeltaEvent

        ev = TextDeltaEvent(text="hi")
        # TextDeltaEvent has no `value` attribute.
        _ = ev.value  # type: ignore[attr-defined]  # <-- intentionally permissive
        # Without the `type: ignore`, mypy would flag this as [attr-defined].
        # Prove that: the positive shape has `.text`, not `.value`.
        hello: str = ev.text
        # Negative probe: assigning `.text` to int fails assignment.
        wrong: int = ev.text
    ''')
    _, consumer = _write_pair(tmp_path, consumer_body)
    code, out, _err = _run_mypy(consumer, strict=False)
    assert code != 0, f"mypy should fail; got clean output:\n{out}"
    codes = _error_codes(out)
    # 'assignment' = incompatible types in assignment (str → int).
    assert "assignment" in codes, f"expected [assignment], got {codes}\n{out}"


# ---------- Meta-check: mypy config / error-code detection actually works ----------


def test_meta_mypy_emits_codes_in_format_we_parse(tmp_path: Path):
    """Guard the _error_codes helper against mypy output format changes."""
    bad = tmp_path / "bad.py"
    bad.write_text("x: int = 'not-an-int'\n")
    code, out, _err = _run_mypy(bad)
    assert code != 0
    assert "assignment" in _error_codes(out), (
        f"mypy output format may have changed; got:\n{out}"
    )
