import * as fs from "fs-extra";
import path from "path";
import yaml from "js-yaml";

function extractFrontmatter<T = any>(content: string): { attributes: T } {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    return { attributes: {} as T };
  }
  const attributes = yaml.load(match[1]) as T;
  return { attributes: attributes || ({} as T) };
}

// Lazily load json-schema-to-typescript to avoid cwd access at startup
let _compile: ((schema: any, name: string, opts: any) => Promise<string>) | null = null;
async function getCompile() {
  if (_compile) return _compile;
  const mod = await import("json-schema-to-typescript");
  // Support both ESM/CJS interop shapes
  const c = (mod as any).compile || (mod as any).default?.compile;
  _compile = c.bind(mod);
  return _compile!;
}

type TextPromptFrontmatterV1_0 = {
  path: string;
  version: "1.0";
  text_config: {
    model_name: string;
    tools?: string[];
  };
  input_schema?: any;
};

type ObjectPromptFrontmatterV1_0 = {
  path: string;
  version: "1.0";
  object_config: {
    model_name: string;
    schema: any;
    tools?: Record<string, any>;
  };
  input_schema?: any;
};

type ImagePromptFrontmatterV1_0 = {
  path: string;
  version: "1.0";
  image_config: {
    model_name: string;
    tools?: Record<string, any>;
  };
  input_schema?: any;
};

type PromptFrontmatterV0 = {
  path: string;
  metadata: {
    model?: {
      settings?: {
        schema?: any;
        tools?: Record<string, any>;
      };
    };
  };
  input_schema?: any;
  version?: "0.0";
};

type PromptFrontmatter =
  | PromptFrontmatterV0
  | TextPromptFrontmatterV1_0
  | ObjectPromptFrontmatterV1_0
  | ImagePromptFrontmatterV1_0;

function getInterfaceName(filePath: string): string {
  return filePath
    .replace(/\.prompt\.mdx$/, "")
    .split("/")
    .map((part) => {
      // Handle snake_case, camelCase, and kebab-case
      return part
        .split(/[-_]|(?=[A-Z])/)
        .map(
          (word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
        )
        .join("")
        .replace(/[^a-zA-Z0-9]/g, "");
    })
    .join("$");
}

function getToolInterfaceName(toolName: string): string {
  return toolName
    .split(/[-_]|(?=[A-Z])/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

export async function findPromptFiles(dir: string): Promise<string[]> {
  const files = await fs.readdir(dir, { withFileTypes: true });
  let promptFiles: string[] = [];

  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      promptFiles = promptFiles.concat(await findPromptFiles(fullPath));
    } else if (file.name.endsWith(".prompt.mdx")) {
      promptFiles.push(fullPath);
    }
  }

  return promptFiles;
}

async function generateTypeDefinitionsV1_0(
  prompts:
    | TextPromptFrontmatterV1_0[]
    | ObjectPromptFrontmatterV1_0[]
    | ImagePromptFrontmatterV1_0[]
): Promise<string> {
  const interfaces: string[] = [];
  const headerComment = `// Auto-generated types from AgentMark
// Do not edit this file directly

`;
  let output = "";
  const typeMapping: string[] = [];

  for (const prompt of prompts) {
    const { path: promptPath, input_schema } = prompt;
    const name = getInterfaceName(promptPath);
    let tools: any = {};
    try {
      let kind = "text";
      let output_schema = null;

      if ("text_config" in prompt) {
        kind = "text";
        tools = prompt.text_config.tools || {};
      } else if ("object_config" in prompt) {
        kind = "object";
        tools = prompt.object_config.tools || {};
        output_schema = prompt.object_config.schema;
      } else if ("image_config" in prompt) {
        kind = "image";
        tools = prompt.image_config.tools || {};
      }

      const compile = await getCompile();
      const inputInterface = input_schema
        ? await compile(input_schema, `${name}In`, {
            bannerComment: "",
            additionalProperties: false,
          })
        : `interface ${name}In { [key: string]: any }`;
      const toolTypes = await generateToolTypes(tools);
      const outputInterface = output_schema
        ? await compile(output_schema, `${name}Out`, {
            bannerComment: "",
            additionalProperties: false,
          })
        : `type ${name}Out = string`;

      interfaces.push(
        inputInterface.replace("export interface", "interface"),
        outputInterface
          .replace("export type", "type")
          .replace("export interface", "interface")
      );

      output += toolTypes || "";

      output += `type ${name} = {
  kind: '${kind}';
  input:  ${name}In;
  output: ${name}Out;${
        toolTypes
          ? `
  tools?: Array<keyof Tools>;`
          : ""
      }
};\n\n`;

      // Generate all path variants for type-safe access:
      // - "greeting.prompt.mdx" (full path)
      // - "greeting.prompt" (without .mdx)
      // - "greeting" (short name)
      typeMapping.push(`  "${promptPath}": ${name}`);
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath) {
        typeMapping.push(`  "${withoutMdx}": ${name}`);
      }
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push(`  "${shortName}": ${name}`);
      }
    } catch (error) {
      console.error(`Error processing ${promptPath}:`, error);
      interfaces.push(
        `interface ${name}In { [key: string]: any }
type ${name}Out = string`
      );
    }
  }

  output += `export default interface AgentmarkTypes {
${typeMapping.join(",\n")}
}\n`;

  return headerComment + interfaces.join("\n\n") + "\n\n" + output;
}

async function generateTypeDefinitionsV0(
  prompts: PromptFrontmatterV0[]
): Promise<string> {
  const interfaces: string[] = [];
  const headerComment = `// Auto-generated types from AgentMark
// Do not edit this file directly

`;
  let output = "";
  const typeMapping: string[] = [];

  for (const prompt of prompts) {
    const { path: promptPath, metadata, input_schema } = prompt;
    const name = getInterfaceName(promptPath);

    try {
      const compile = await getCompile();
      const inputInterface = input_schema
        ? await compile(input_schema, `${name}In`, {
            bannerComment: "",
            additionalProperties: false,
          })
        : `interface ${name}In { [key: string]: any }`;

      const outputSchema = metadata?.model?.settings?.schema;

      const outputInterface = outputSchema
        ? await compile(outputSchema, `${name}Out`, {
            bannerComment: "",
            additionalProperties: false,
          })
        : `type ${name}Out = string`;

      interfaces.push(
        inputInterface.replace("export interface", "interface"),
        outputInterface
          .replace("export type", "type")
          .replace("export interface", "interface")
      );

      output += `interface ${name} {
  input: ${name}In;
  output: ${name}Out;
}\n\n`;

      // Generate all path variants for type-safe access:
      // - "greeting.prompt.mdx" (full path)
      // - "greeting.prompt" (without .mdx)
      // - "greeting" (short name)
      typeMapping.push(`  "${promptPath}": ${name}`);
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath) {
        typeMapping.push(`  "${withoutMdx}": ${name}`);
      }
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push(`  "${shortName}": ${name}`);
      }
    } catch (error: any) {
      console.error(`Error processing ${promptPath}:`, error);
      interfaces.push(
        `interface ${name}In { [key: string]: any }
type ${name}Out = string`
      );

      output += `interface ${name} {
  input: ${name}In;
  output: ${name}Out;
}\n\n`;

      // Generate all path variants for type-safe access even on error
      typeMapping.push(`  "${promptPath}": ${name}`);
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath) {
        typeMapping.push(`  "${withoutMdx}": ${name}`);
      }
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push(`  "${shortName}": ${name}`);
      }
    }
  }

  output += `export default interface AgentmarkTypes {
${typeMapping.join(",\n")}
}\n`;

  return headerComment + interfaces.join("\n\n") + "\n\n" + output;
}

const isNewFormat = (frontmatter: any) => {
  return (
    frontmatter["text_config"] ||
    frontmatter["object_config"] ||
    frontmatter["image_config"]
  );
};

// =============================================================================
// Python TypedDict generation
// =============================================================================

function pythonPrimitiveType(schemaType: string): string {
  const map: Record<string, string> = {
    string: "str",
    number: "float",
    integer: "int",
    boolean: "bool",
    null: "None",
  };
  return map[schemaType] || "Any";
}

function propToPascal(prop: string): string {
  return prop
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/**
 * Recursively convert a JSON Schema to a Python type annotation string.
 * For nested object types, creates TypedDict classes and appends them to `collected`.
 */
function schemaToPythonType(
  schema: any,
  parentClass: string,
  propKey: string,
  collected: string[]
): string {
  if (!schema) return "Any";

  // anyOf / oneOf (commonly used for nullable types)
  const union = schema.anyOf || schema.oneOf;
  if (union) {
    const nullIdx = union.findIndex((v: any) => v.type === "null");
    const hasNull = nullIdx >= 0;
    const others = union.filter((_: any, i: number) => i !== nullIdx);

    if (hasNull && others.length === 1) {
      return `${schemaToPythonType(others[0], parentClass, propKey, collected)} | None`;
    }
    const parts = others.map((v: any, i: number) =>
      schemaToPythonType(v, parentClass, `${propKey}${i}`, collected)
    );
    if (hasNull) parts.push("None");
    return parts.join(" | ");
  }

  // Type arrays: ["string", "null"] → str | None
  if (Array.isArray(schema.type)) {
    const hasNull = schema.type.includes("null");
    const nonNull = schema.type.filter((t: string) => t !== "null");

    // ["object", "null"] with properties → TypedDict | None
    if (nonNull.length === 1 && nonNull[0] === "object" && schema.properties) {
      const clsName = `${parentClass}${propToPascal(propKey)}`;
      collected.push(buildTypedDict(clsName, schema, collected));
      return hasNull ? `${clsName} | None` : clsName;
    }

    // ["array", "null"] with items → list[T] | None
    if (nonNull.length === 1 && nonNull[0] === "array" && schema.items) {
      const item = schemaToPythonType(
        schema.items,
        parentClass,
        propKey,
        collected
      );
      return hasNull ? `list[${item}] | None` : `list[${item}]`;
    }

    const base =
      nonNull.length === 1
        ? pythonPrimitiveType(nonNull[0])
        : nonNull.map(pythonPrimitiveType).join(" | ");
    return hasNull ? `${base} | None` : base;
  }

  switch (schema.type) {
    case "string":
    case "number":
    case "integer":
    case "boolean":
    case "null":
      return pythonPrimitiveType(schema.type);

    case "array": {
      const item = schema.items
        ? schemaToPythonType(schema.items, parentClass, propKey, collected)
        : "Any";
      return `list[${item}]`;
    }

    case "object": {
      if (!schema.properties || Object.keys(schema.properties).length === 0) {
        return "dict[str, Any]";
      }
      const clsName = `${parentClass}${propToPascal(propKey)}`;
      collected.push(buildTypedDict(clsName, schema, collected));
      return clsName;
    }

    default:
      // No explicit type but has properties — treat as object
      if (schema.properties) {
        const clsName = `${parentClass}${propToPascal(propKey)}`;
        collected.push(buildTypedDict(clsName, schema, collected));
        return clsName;
      }
      return "Any";
  }
}

/**
 * Build a Python TypedDict class definition from an object JSON Schema.
 * Nested objects are extracted into separate classes and appended to `collected`.
 */
function buildTypedDict(
  className: string,
  schema: any,
  collected: string[]
): string {
  const props = schema.properties || {};
  const requiredSet = new Set<string>(schema.required || []);
  const lines: string[] = [];
  const desc = schema.description;

  if (desc) {
    lines.push(`class ${className}(TypedDict):`);
    lines.push(`    """${desc}"""`);
  } else {
    lines.push(`class ${className}(TypedDict):`);
  }

  const entries = Object.entries(props);
  if (entries.length === 0) {
    lines.push("    pass");
    return lines.join("\n");
  }

  for (const [key, propSchema] of entries) {
    const pyType = schemaToPythonType(
      propSchema as any,
      className,
      key,
      collected
    );
    const isRequired = requiredSet.has(key);
    const annotation = isRequired ? pyType : `NotRequired[${pyType}]`;
    const propDesc = (propSchema as any).description;

    if (propDesc) {
      const prefix = `    ${key}: ${annotation}  # `;
      const maxDesc = 99 - prefix.length;
      if (maxDesc > 10) {
        const shortDesc =
          propDesc.length > maxDesc
            ? propDesc.substring(0, maxDesc - 3) + "..."
            : propDesc;
        lines.push(`${prefix}${shortDesc}`);
      } else {
        // Annotation itself is already near 100 chars — skip comment
        lines.push(`    ${key}: ${annotation}`);
      }
    } else {
      lines.push(`    ${key}: ${annotation}`);
    }
  }

  return lines.join("\n");
}

function generatePythonToolTypes(tools: Record<string, any>): string | null {
  if (Object.keys(tools).length === 0) return null;

  const collected: string[] = [];

  for (const [toolName, schema] of Object.entries(tools)) {
    const argsName = `${getToolInterfaceName(toolName)}Args`;
    if (schema.parameters && schema.parameters.properties) {
      collected.push(buildTypedDict(argsName, schema.parameters, collected));
    } else {
      collected.push(`class ${argsName}(TypedDict):\n    pass`);
    }
  }

  const toolLines = Object.keys(tools)
    .map((name) => `    ${name}: ${getToolInterfaceName(name)}Args`)
    .join("\n");
  collected.push(`class Tools(TypedDict):\n${toolLines}`);

  return collected.join("\n\n\n");
}

function buildPythonHeader(body: string): string {
  const imports: string[] = ["TypedDict"];
  if (body.includes("NotRequired[")) imports.push("NotRequired");
  if (body.includes("Literal[")) imports.push("Literal");
  if (/\bAny\b/.test(body)) imports.push("Any");
  imports.sort();
  return `# Auto-generated types from AgentMark
# Do not edit this file directly

from __future__ import annotations

from typing import ${imports.join(", ")}


`;
}

async function generatePythonTypeDefinitionsV1_0(
  prompts: (
    | TextPromptFrontmatterV1_0
    | ObjectPromptFrontmatterV1_0
    | ImagePromptFrontmatterV1_0
  )[]
): Promise<string> {

  const allClasses: string[] = [];
  const typeMapping: { path: string; name: string }[] = [];

  for (const prompt of prompts) {
    const { path: promptPath, input_schema } = prompt;
    const name = getInterfaceName(promptPath);

    try {
      let kind = "text";
      let outputSchema = null;
      let tools: any = {};

      if ("text_config" in prompt) {
        kind = "text";
        tools = prompt.text_config.tools || {};
      } else if ("object_config" in prompt) {
        kind = "object";
        tools = prompt.object_config.tools || {};
        outputSchema = prompt.object_config.schema;
      } else if ("image_config" in prompt) {
        kind = "image";
        tools = prompt.image_config.tools || {};
      }

      // Input class
      const inputCollected: string[] = [];
      if (input_schema && input_schema.properties) {
        inputCollected.push(
          buildTypedDict(`${name}In`, input_schema, inputCollected)
        );
      } else {
        inputCollected.push(`class ${name}In(TypedDict):\n    pass`);
      }
      allClasses.push(...inputCollected);

      // Output class
      const outputCollected: string[] = [];
      if (outputSchema && outputSchema.properties) {
        outputCollected.push(
          buildTypedDict(`${name}Out`, outputSchema, outputCollected)
        );
      } else if (kind === "object") {
        outputCollected.push(`class ${name}Out(TypedDict):\n    pass`);
      } else {
        outputCollected.push(`${name}Out = str`);
      }
      allClasses.push(...outputCollected);

      // Tool types
      if (Object.keys(tools).length > 0) {
        const toolOutput = generatePythonToolTypes(tools);
        if (toolOutput) allClasses.push(toolOutput);
      }

      // Prompt type class
      const toolsLine =
        Object.keys(tools).length > 0
          ? "\n    tools: NotRequired[list[str]]"
          : "";
      allClasses.push(
        `class ${name}(TypedDict):\n` +
          `    kind: Literal['${kind}']\n` +
          `    input: ${name}In\n` +
          `    output: ${name}Out${toolsLine}`
      );

      // Path variants
      typeMapping.push({ path: promptPath, name });
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath)
        typeMapping.push({ path: withoutMdx, name });
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push({ path: shortName, name });
      }
    } catch (error) {
      console.error(`Error processing ${promptPath}:`, error);
      allClasses.push(`class ${name}In(TypedDict):\n    pass`);
      allClasses.push(`${name}Out = str`);
      allClasses.push(
        `class ${name}(TypedDict):\n` +
          `    kind: Literal['text']\n` +
          `    input: ${name}In\n` +
          `    output: ${name}Out`
      );
      typeMapping.push({ path: promptPath, name });
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath)
        typeMapping.push({ path: withoutMdx, name });
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push({ path: shortName, name });
      }
    }
  }

  // AgentmarkTypes — functional form since keys contain hyphens
  const mappingLines = typeMapping
    .map(({ path, name }) => `    '${path}': ${name}`)
    .join(",\n");

  allClasses.push(
    `AgentmarkTypes = TypedDict('AgentmarkTypes', {\n${mappingLines},\n})`
  );

  const body = allClasses.join("\n\n\n") + "\n";
  return buildPythonHeader(body) + body;
}

async function generatePythonTypeDefinitionsV0(
  prompts: PromptFrontmatterV0[]
): Promise<string> {
  const allClasses: string[] = [];
  const typeMapping: { path: string; name: string }[] = [];

  for (const prompt of prompts) {
    const { path: promptPath, metadata, input_schema } = prompt;
    const name = getInterfaceName(promptPath);

    try {
      // Input class
      const inputCollected: string[] = [];
      if (input_schema && input_schema.properties) {
        inputCollected.push(
          buildTypedDict(`${name}In`, input_schema, inputCollected)
        );
      } else {
        inputCollected.push(`class ${name}In(TypedDict):\n    pass`);
      }
      allClasses.push(...inputCollected);

      // Output class
      const outputSchema = metadata?.model?.settings?.schema;
      const outputCollected: string[] = [];
      if (outputSchema && outputSchema.properties) {
        outputCollected.push(
          buildTypedDict(`${name}Out`, outputSchema, outputCollected)
        );
      } else {
        outputCollected.push(`${name}Out = str`);
      }
      allClasses.push(...outputCollected);

      // Prompt type class
      allClasses.push(
        `class ${name}(TypedDict):\n` +
          `    input: ${name}In\n` +
          `    output: ${name}Out`
      );

      // Path variants
      typeMapping.push({ path: promptPath, name });
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath)
        typeMapping.push({ path: withoutMdx, name });
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push({ path: shortName, name });
      }
    } catch (error) {
      console.error(`Error processing ${promptPath}:`, error);
      allClasses.push(`class ${name}In(TypedDict):\n    pass`);
      allClasses.push(`${name}Out = str`);
      allClasses.push(
        `class ${name}(TypedDict):\n` +
          `    input: ${name}In\n` +
          `    output: ${name}Out`
      );
      typeMapping.push({ path: promptPath, name });
      const withoutMdx = promptPath.replace(/\.mdx$/, "");
      if (withoutMdx !== promptPath)
        typeMapping.push({ path: withoutMdx, name });
      const shortName = promptPath.replace(/\.prompt\.mdx$/, "");
      if (shortName !== promptPath && shortName !== withoutMdx) {
        typeMapping.push({ path: shortName, name });
      }
    }
  }

  // AgentmarkTypes
  const mappingLines = typeMapping
    .map(({ path, name }) => `    '${path}': ${name}`)
    .join(",\n");

  allClasses.push(
    `AgentmarkTypes = TypedDict('AgentmarkTypes', {\n${mappingLines},\n})`
  );

  const body = allClasses.join("\n\n\n") + "\n";
  return buildPythonHeader(body) + body;
}

export type GenerateTypesLanguage = "typescript" | "python";

export async function generateTypeDefinitions(
  prompts: PromptFrontmatter[],
  language: GenerateTypesLanguage = "typescript"
): Promise<string> {
  if (language === "python") {
    if (prompts[0].version === "1.0") {
      return generatePythonTypeDefinitionsV1_0(prompts as any);
    }
    return generatePythonTypeDefinitionsV0(prompts as any);
  }
  if (prompts[0].version === "1.0") {
    return generateTypeDefinitionsV1_0(prompts as any);
  }
  return generateTypeDefinitionsV0(prompts as any);
}

export async function fetchPromptsFrontmatter(options: {
  local?: number;
  rootDir?: string;
}): Promise<PromptFrontmatter[]> {
  if (options.local) {
    const baseUrl = `http://localhost:${options.local}`;
    try {
      const pathsResponse = await fetch(`${baseUrl}/v1/prompts`);
      if (!pathsResponse.ok) {
        throw new Error(
          `Failed to fetch prompt paths: ${pathsResponse.statusText}`
        );
      }

      const { paths } = await pathsResponse.json();

      return Promise.all(
        paths.map(async (promptPath: string) => {
          const templateResponse = await fetch(
            `${baseUrl}/v1/templates?path=${promptPath}`
          );
          if (!templateResponse.ok) {
            throw new Error(
              `Failed to fetch template ${promptPath}: ${templateResponse.statusText}`
            );
          }

          const { data: ast } = await templateResponse.json();
          const yamlNode = ast.children.find(
            (node: any) => node.type === "yaml"
          );
          if (!yamlNode) {
            throw new Error(`No YAML frontmatter found in ${promptPath}`);
          }

          const { parse: parseYaml } = await import("yaml");
          const frontmatter = parseYaml(yamlNode.value);

          if (isNewFormat(frontmatter)) {
            return {
              path: promptPath,
              ...frontmatter,
              version: "1.0",
            };
          }

          return {
            path: promptPath,
            ...frontmatter,
          };
        })
      );
    } catch (error) {
      if (
        error instanceof TypeError &&
        error.message.includes("fetch failed")
      ) {
        console.error(`Connection failed to ${baseUrl}.`);
      }
      console.error("\nError details:", error);
      throw error;
    }
  }

  if (options.rootDir) {
    if (!fs.existsSync(options.rootDir)) {
      throw new Error(`Directory not found at: ${options.rootDir}`);
    }

    const promptFiles = await findPromptFiles(options.rootDir);

    return Promise.all(
      promptFiles.map(async (file) => {
        const content = await fs.readFile(file, "utf-8");
        const { attributes } = extractFrontmatter(content);

        if (isNewFormat(attributes)) {
          return {
            path: path.relative(options.rootDir!, file),
            ...attributes,
            version: "1.0",
          };
        }
        return {
          path: path.relative(options.rootDir!, file),
          ...attributes,
        };
      })
    );
  }

  throw new Error("Either --local or --root-dir must be specified");
}

async function generateToolTypes(tools: Record<string, any>) {
  const toolArgTypes: string[] = [];

  for (const [toolName, schema] of Object.entries(tools)) {
    const typeName = `${getToolInterfaceName(toolName)}Args`;

    try {
      const compile = await getCompile();
      const argInterface = schema.parameters
        ? await compile(schema.parameters, typeName, {
            bannerComment: "",
            additionalProperties: false,
          })
        : `type ${typeName} = { ${Object.entries(schema.parameters || {})
            .map(([key]) => `${key}: any`)
            .join("; ")} };`;

      toolArgTypes.push(
        argInterface
          .replace("export type", "type")
          .replace("export interface", "interface")
      );
    } catch (error) {
      console.error(`Error processing tool ${toolName}:`, error);
      toolArgTypes.push(`type ${typeName} = { [key: string]: any };`);
    }
  }

  if (Object.keys(tools).length > 0) {
    // Generate the Tools interface that combines all tool types
    const toolsInterface = `export interface Tools {
${Object.keys(tools)
  .map(
    (toolName) =>
      `  ${toolName}: { args: ${getToolInterfaceName(toolName)}Args };`
  )
  .join("\n")}
}`;

    return toolArgTypes.join("\n\n") + "\n\n" + toolsInterface + "\n\n";
  }

  return null;
}
