export const getTypesFileContent = (): string => {
  return `// Auto-generated types for AgentMark
// Do not edit this file directly

interface ObjectEntry<I, O> { kind: 'object'; input: I; output: O }
interface TextEntry<I, O>   { kind: 'text';   input: I; output: O }
interface ImageEntry<I, O>  { kind: 'image';  input: I; output: O }

// Types for customer-reply.prompt.mdx
interface CustomerReplyIn {
  /**
   * The customer's question
   */
  customer_question: string;
}

// Types for response-quality-eval.prompt.mdx
interface ResponseQualityEvalIn {
  /**
   * The output from the model to evaluate
   */
  model_output: string;
  
  /**
   * The customer's message that the model was responding to
   */
  customer_message: string;
}

interface ResponseQualityEvalOut {
  /**
   * Evaluation score from 0 to 10
   */
  score: number;
  
  /**
   * A label for the evaluation (e.g. "excellent", "good", "poor")
   */
  label: string;
  
  /**
   * Reason for the given score and label
   */
  reason: string;
}

type CustomerReply = TextEntry<CustomerReplyIn, string>;
type ResponseQualityEval = ObjectEntry<ResponseQualityEvalIn, ResponseQualityEvalOut>;

interface AgentMarkTypes {
  "customer-reply.prompt.mdx": CustomerReply,
  "response-quality-eval.prompt.mdx": ResponseQualityEval,
}

export default AgentMarkTypes;
`;
}; 