export const getTypesFileContent = (): string => {
  return `// Auto-generated types from AgentMark
// Do not edit this file directly

interface CustomerReplyIn {
  /**
   * The customer's question
   */
  customer_question: string;
}


type CustomerReplyOut = string

interface ResponseQualityEvalIn {
  /**
   * The customer's message
   */
  customer_message: string;
  /**
   * The model's output
   */
  model_output: string;
}


interface ResponseQualityEvalOut {
  /**
   * The score of the response
   */
  score: number;
  /**
   * The label of the response
   */
  label: string;
  /**
   * The reason for the score
   */
  reason: string;
}


type CustomerReply = {
  kind: 'text';
  input:  CustomerReplyIn;
  output: CustomerReplyOut;
};

type ResponseQualityEval = {
  kind: 'object';
  input:  ResponseQualityEvalIn;
  output: ResponseQualityEvalOut;
};

export default interface AgentmarkTypes {
  "customer-reply.prompt.mdx": CustomerReply,
  "response-quality-eval.prompt.mdx": ResponseQualityEval
}
`;
}; 