export const getTypesFileContent = (): string => {
  return `// Auto-generated types from AgentMark
// Do not edit this file directly

interface AnimalDrawingIn {
  /**
   * The animal to draw
   */
  animal: string;
}

type AnimalDrawingOut = string;

interface CustomerSupportIn {
  /**
   * The customer's question
   */
  customer_question: string;
}

type CustomerSupportOut = string;

interface PartyPlannerIn {
  /**
   * A block of text describing the upcoming party and attendees
   */
  party_text: string;
}

interface PartyPlannerOut {
  /**
   * List of names of people attending the party
   */
  names: string[];
}

interface StoryTellerIn {
  /**
   * The story to tell
   */
  story: string;
}

type StoryTellerOut = string;

type AnimalDrawing = {
  kind: 'image';
  input: AnimalDrawingIn;
  output: AnimalDrawingOut;
};

type CustomerSupport = {
  kind: 'text';
  input: CustomerSupportIn;
  output: CustomerSupportOut;
};

type PartyPlanner = {
  kind: 'object';
  input: PartyPlannerIn;
  output: PartyPlannerOut;
};

type StoryTeller = {
  kind: 'speech';
  input: StoryTellerIn;
  output: StoryTellerOut;
};

export default interface AgentmarkTypes {
  "animal-drawing.prompt.mdx": AnimalDrawing,
  "customer-support.prompt.mdx": CustomerSupport,
  "party-planner.prompt.mdx": PartyPlanner,
  "story-teller.prompt.mdx": StoryTeller
}
`;
}; 