import { describe, it, expect } from "vitest";
import { generateTypeDefinitions } from "../src/generate-types";

// The TypeScript path delegates schema→interface compilation to
// json-schema-to-typescript (asserted only loosely), but the orchestration —
// kind detection, hasTools logic, the prompt-type block, the AgentmarkTypes
// mapping and its path variants — is deterministic and asserted exactly.

const ts = (prompts: any[]) => generateTypeDefinitions(prompts, "typescript");

describe("generateTypeDefinitions (typescript) — deterministic whole-file output", () => {
  it("text prompt with no schemas/tools renders exactly", async () => {
    const out = await ts([
      { path: "greet.prompt.mdx", version: "1.0", text_config: { model_name: "m" } },
    ]);
    expect(out).toBe(
      `// Auto-generated types from AgentMark
// Do not edit this file directly

interface GreetIn { [key: string]: any }

type GreetOut = string

type Greet = {
  kind: 'text';
  input:  GreetIn;
  output: GreetOut;
};

export default interface AgentmarkTypes {
  "greet.prompt.mdx": Greet,
  "greet.prompt": Greet,
  "greet": Greet
}
`
    );
  });

  it("image prompt sets kind 'image'", async () => {
    const out = await ts([
      { path: "pic.prompt.mdx", version: "1.0", image_config: { model_name: "m" } },
    ]);
    expect(out).toContain(`type Pic = {
  kind: 'image';
  input:  PicIn;
  output: PicOut;
};`);
  });
});

describe("generateTypeDefinitions (typescript) — object prompt + tools", () => {
  const obj = {
    path: "math/add.prompt.mdx",
    version: "1.0",
    object_config: {
      model_name: "m",
      schema: { type: "object", properties: { answer: { type: "integer" } }, required: ["answer"] },
      tools: ["lookup"],
    },
  };

  it("sets kind 'object' and emits a tools line", async () => {
    expect(await ts([obj])).toContain(`type Math$Add = {
  kind: 'object';
  input:  Math$AddIn;
  output: Math$AddOut;
  tools?: string[];
};`);
  });

  it("compiles the object_config.schema into the output interface", async () => {
    const out = await ts([obj]);
    expect(out).toContain("interface Math$AddOut {");
    expect(out).toContain("answer: number;");
  });
});

describe("generateTypeDefinitions (typescript) — hasTools detection", () => {
  const withTools = (tools: any) => ts([
    { path: "t.prompt.mdx", version: "1.0", text_config: { model_name: "m", tools } },
  ]);

  it("omits the tools line for an empty tools array", async () => {
    expect(await withTools([])).not.toContain("tools?: string[];");
  });

  it("emits the tools line for a non-empty tools array", async () => {
    expect(await withTools(["a"])).toContain("tools?: string[];");
  });

  it("emits the tools line for a truthy non-array tools value (object_config path)", async () => {
    const out = await ts([
      {
        path: "o.prompt.mdx",
        version: "1.0",
        object_config: { model_name: "m", schema: { type: "object", properties: {} }, tools: { x: {} } },
      },
    ]);
    expect(out).toContain("tools?: string[];");
  });
});

describe("generateTypeDefinitions (typescript) — V0 prompts", () => {
  it("renders an interface with no kind line and string output when no schema", async () => {
    const out = await ts([
      { path: "old/thing.prompt.mdx", metadata: { model: { settings: {} } } },
    ]);
    expect(out).toContain(`interface Old$Thing {
  input: Old$ThingIn;
  output: Old$ThingOut;
}`);
    expect(out).toContain("type Old$ThingOut = string");
    expect(out).not.toContain("kind:");
  });

  it("compiles metadata.model.settings.schema into the output interface", async () => {
    const out = await ts([
      {
        path: "o.prompt.mdx",
        metadata: { model: { settings: { schema: { type: "object", properties: { ok: { type: "boolean" } } } } } },
      },
    ]);
    expect(out).toContain("interface OOut {");
    expect(out).toContain("ok?: boolean;");
  });
});

describe("generateTypeDefinitions (typescript) — path variants", () => {
  it("emits all three variants for a *.prompt.mdx path", async () => {
    const out = await ts([
      { path: "a/b.prompt.mdx", version: "1.0", text_config: {} },
    ]);
    expect(out).toContain(`export default interface AgentmarkTypes {
  "a/b.prompt.mdx": A$B,
  "a/b.prompt": A$B,
  "a/b": A$B
}`);
  });

  it("emits a single mapping entry when the path has no .mdx / .prompt.mdx suffix", async () => {
    const out = await ts([
      { path: "plain", version: "1.0", text_config: {} },
    ]);
    expect(out).toContain(`export default interface AgentmarkTypes {
  "plain": Plain
}`);
  });
});
