import { describe, it, expect } from "vitest";
import { generateTypeDefinitions } from "../src/generate-types";

// The Python generator is fully self-contained (no external compiler), so we
// assert exact output. These pin schemaToPythonType / buildTypedDict /
// pythonPrimitiveType / propToPascal / getInterfaceName / buildPythonHeader /
// generatePythonToolTypes and the V0 vs V1.0 prompt-class shapes.

const py = (prompts: any[]) => generateTypeDefinitions(prompts, "python");

describe("generateTypeDefinitions (python) — V1.0 text prompt", () => {
  it("emits exact output: text kind, str output, no tools line, sorted imports, path variants", async () => {
    const out = await py([
      { path: "greet.prompt.mdx", version: "1.0", text_config: { model_name: "gpt-4o" } },
    ]);
    expect(out).toBe(
      `# Auto-generated types from AgentMark
# Do not edit this file directly

from __future__ import annotations

from typing import Literal, TypedDict


class GreetIn(TypedDict):
    pass


GreetOut = str


class Greet(TypedDict):
    kind: Literal['text']
    input: GreetIn
    output: GreetOut


AgentmarkTypes = TypedDict('AgentmarkTypes', {
    'greet.prompt.mdx': Greet,
    'greet.prompt': Greet,
    'greet': Greet,
})
`
    );
  });
});

describe("generateTypeDefinitions (python) — V0 prompt", () => {
  it("emits exact output: no kind line, output from metadata schema, NotRequired import", async () => {
    const out = await py([
      {
        path: "old/thing.prompt.mdx",
        metadata: { model: { settings: { schema: { type: "object", properties: { out: { type: "string" } } } } } },
        input_schema: { type: "object", properties: { q: { type: "string" } }, required: ["q"] },
      },
    ]);
    expect(out).toBe(
      `# Auto-generated types from AgentMark
# Do not edit this file directly

from __future__ import annotations

from typing import NotRequired, TypedDict


class Old$ThingIn(TypedDict):
    q: str


class Old$ThingOut(TypedDict):
    out: NotRequired[str]


class Old$Thing(TypedDict):
    input: Old$ThingIn
    output: Old$ThingOut


AgentmarkTypes = TypedDict('AgentmarkTypes', {
    'old/thing.prompt.mdx': Old$Thing,
    'old/thing.prompt': Old$Thing,
    'old/thing': Old$Thing,
})
`
    );
  });
});

describe("generateTypeDefinitions (python) — V1.0 object prompt with rich schema + tools", () => {
  const objV1 = {
    path: "math/add.prompt.mdx",
    version: "1.0",
    object_config: {
      model_name: "gpt-4o",
      schema: { type: "object", properties: { answer: { type: "integer" } }, required: ["answer"] },
      tools: { lookup: { parameters: { type: "object", properties: { q: { type: "string" } }, required: ["q"] } } },
    },
    input_schema: {
      type: "object",
      properties: {
        name: { type: "string", description: "The name" },
        age: { type: "integer" },
        tags: { type: "array", items: { type: "string" } },
        nick: { anyOf: [{ type: "string" }, { type: "null" }] },
        addr: { type: "object", properties: { city: { type: "string" } }, required: ["city"] },
        meta: { type: "object" },
        flag: { type: "boolean" },
        score: { type: "number" },
      },
      required: ["name", "addr"],
    },
  };

  it("nested object becomes a separate TypedDict named <Parent><Prop>", async () => {
    expect(await py([objV1])).toContain("class Math$AddInAddr(TypedDict):\n    city: str");
  });

  it("maps every primitive + required/optional + nullable + array + empty-object correctly", async () => {
    expect(await py([objV1])).toContain(
      `class Math$AddIn(TypedDict):
    name: str  # The name
    age: NotRequired[int]
    tags: NotRequired[list[str]]
    nick: NotRequired[str | None]
    addr: Math$AddInAddr
    meta: NotRequired[dict[str, Any]]
    flag: NotRequired[bool]
    score: NotRequired[float]`
    );
  });

  it("emits the object output class from object_config.schema", async () => {
    expect(await py([objV1])).toContain("class Math$AddOut(TypedDict):\n    answer: int");
  });

  it("emits tool arg TypedDicts and a Tools class", async () => {
    const out = await py([objV1]);
    expect(out).toContain("class LookupArgs(TypedDict):\n    q: str");
    expect(out).toContain("class Tools(TypedDict):\n    lookup: LookupArgs");
  });

  it("prompt class carries kind 'object' and a tools line when tools exist", async () => {
    expect(await py([objV1])).toContain(
      `class Math$Add(TypedDict):
    kind: Literal['object']
    input: Math$AddIn
    output: Math$AddOut
    tools: NotRequired[list[str]]`
    );
  });

  it("header imports are sorted and include Any (empty object) + Literal (kind) + NotRequired", async () => {
    expect(await py([objV1])).toContain("from typing import Any, Literal, NotRequired, TypedDict");
  });
});

describe("generateTypeDefinitions (python) — schema → python type edge cases", () => {
  // Drive schemaToPythonType through buildTypedDict on a required field so the
  // annotation is the bare python type (no NotRequired wrapper).
  async function annotationFor(schema: any): Promise<string> {
    const out = await py([
      {
        path: "t.prompt.mdx",
        version: "1.0",
        text_config: {},
        input_schema: { type: "object", properties: { f: schema }, required: ["f"] },
      },
    ]);
    const m = out.match(/^    f: (.+)$/m);
    return m ? m[1] : "<none>";
  }

  it("number → float, integer → int, boolean → bool, null → None", async () => {
    expect(await annotationFor({ type: "number" })).toBe("float");
    expect(await annotationFor({ type: "integer" })).toBe("int");
    expect(await annotationFor({ type: "boolean" })).toBe("bool");
    expect(await annotationFor({ type: "null" })).toBe("None");
  });

  it("unknown/absent type without properties → Any", async () => {
    expect(await annotationFor({ type: "weird" })).toBe("Any");
    expect(await annotationFor({})).toBe("Any");
  });

  it("type array [\"string\", \"null\"] → str | None", async () => {
    expect(await annotationFor({ type: ["string", "null"] })).toBe("str | None");
  });

  it("type array [\"array\", \"null\"] with items → list[str] | None", async () => {
    expect(await annotationFor({ type: ["array", "null"], items: { type: "string" } })).toBe(
      "list[str] | None"
    );
  });

  it("oneOf with two non-null members → A | B", async () => {
    expect(await annotationFor({ oneOf: [{ type: "string" }, { type: "integer" }] })).toBe(
      "str | int"
    );
  });

  it("array of numbers → list[float]", async () => {
    expect(await annotationFor({ type: "array", items: { type: "number" } })).toBe("list[float]");
  });

  it("array without items → list[Any]", async () => {
    expect(await annotationFor({ type: "array" })).toBe("list[Any]");
  });
});

describe("generateTypeDefinitions (python) — naming + multi-prompt", () => {
  it("getInterfaceName handles kebab, snake and camel segments and joins paths with $", async () => {
    const out = await py([
      { path: "my-dir/my_cool-prompt.prompt.mdx", version: "1.0", text_config: {} },
    ]);
    expect(out).toContain("class MyDir$MyCoolPrompt(TypedDict):");
  });

  it("renders one mapping entry per prompt", async () => {
    const out = await py([
      { path: "a.prompt.mdx", version: "1.0", text_config: {} },
      { path: "b.prompt.mdx", version: "1.0", text_config: {} },
    ]);
    expect(out).toContain("'a.prompt.mdx': A");
    expect(out).toContain("'b.prompt.mdx': B");
  });
});
