// Auto-generated types from Puzzlet
// Do not edit this file directly

type WeatherArgs = { location: string };
type ExplainArgs = { topic: string };

export interface Tools {
  weather: { args: WeatherArgs };
  explain: { args: ExplainArgs };
}

interface ObjectEntry<I, O> { kind: 'object'; input: I; output: O }
interface TextEntry<I, O>   { kind: 'text';   input: I; output: O }
interface ImageEntry<I, O>  { kind: 'image';  input: I; output: O }

interface MathIn { [key: string]: any }

interface MathOut { [key: string]: string }

interface Test$Math2In {
  /**
   * The math question or topic the student needs help with
   */
  userMessage: string;
}


interface Test$Math2Out {
  /**
   * The answer to the math question
   */
  answer: string;
}


type Math = { kind: 'object'; input: MathIn; output: MathOut };

type Test$Math2 = {
  kind: 'text';
  input:  Test$Math2In;
  output: Test$Math2Out;
  tools?: Array<keyof Tools>;
};

interface PuzzletTypes {
  "math.prompt.mdx": Math,
  "test/math2.prompt.mdx": Test$Math2,
}

export default PuzzletTypes;