name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build Docusaurus site
        run: yarn build
        working-directory: ./docs

      - name: Deploy to GitHub Pages
        run: yarn deploy
        working-directory: ./docs
        env:
          GIT_USER: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
