# .github/workflows/notify-cursor.yml
name: Notify Cursor on Labeled Issue

permissions:
  contents: read

on:
  issues:
    types: [labeled]

jobs:
  slack-notify:
    # Run only if the label that was just applied is exactly "cursor"
    if: github.event.label.name == 'cursor'
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Slack
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          CHANNEL_ID:       ${{ secrets.SLACK_CHANNEL_ID }}
          CURSOR_BOT_ID:     ${{ secrets.CURSOR_BOT_ID }}
        run: |
          mention="<@$CURSOR_BOT_ID>"
          text="$mention\n\nFix this issue:\n${{ github.event.issue.body }}"

          curl -s -X POST \
            -H "Authorization: Bearer $SLACK_USER_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$(jq -n \
                      --arg channel "$CHANNEL_ID" \
                      --arg text "$text" \
                      '{channel:$channel, text:$text, link_names:1}')" \
            https://slack.com/api/chat.postMessage