# .github/workflows/notify-cursor.yml
name: Notify Cursor on Labeled Issue

on:
  issues:
    types: [labeled]

jobs:
  slack-notify:
    # Run only if the label that was just applied is exactly "cursor"
    if: github.event.label.name == 'cursor'
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CURSOR_BOT_WEBHOOK }}
        run: |
          payload=$(jq -n \
            --arg body "${{ github.event.issue.body }}" \
            '{
               text: "@Cursor\n\nFix this issue:\n" + $body
             }')

          curl -s -X POST -H 'Content-Type: application/json' \
               --data "$payload" "$SLACK_WEBHOOK_URL"
